name: Campsite
version: '${project.version}'
main: org.morey.shoot.shoot.Campsite
api-version: '1.21'
authors: [Morey]
commands:
  start:
    description: Permet de lancer le jeu
    permission-message: "&cVous n'avez pas les permissions requises."
    permission: campsite.admin.start
  tcreate:
    description: Permet de créer les équipes
    permission-message: "&cVous n'avez pas les permissions requises."
    permission: campsite.admin.tcreate
  stopgame:
    description: Réinitialise la partie
    permission-message: "&cVous n'avez pas les permissions requises."
    permission: campsite.admin.stopgame
  timer:
    description: Voir le timer
    permission-message: "&cVous n'avez pas les permissions requises."
    permission: campsite.base.timer
  spawnall:
    description: Envoie tous les joueurs au spawn
    permission-message: "&cVous n'avez pas les permissions requises."
    permission: campsite.admin.spawnall
  csteam:
    description: Commande de team
    permission: campsite.admin.team
  createteam:
    description: Commande de team
    permission: campsite.admin.createteam

